/**
 * faqSeederHelper.js
 * Aggregates all hand-curated FAQs (faq.json), extended FAQs (faq_extended.json),
 * and their aliases into a single unified array.
 */

const faqs = require('../data/faq.json');
const extendedFaqs = require('../data/faq_extended.json');

function getAllCuratedDocs() {
  const curatedBase = faqs.map(f => ({ ...f, type: 'curated' }));
  const extendedBase = extendedFaqs.map(f => ({ ...f, type: 'curated' }));
  const allBase = [...curatedBase, ...extendedBase];

  // 1. Curated aliases (from seedMongo.js)
  const curatedAliases = [
    { id: 'alias_001_a', question: 'how much money do I need to start algo trading?', answer: faqs.find(f=>f.id==='faq_001')?.answer },
    { id: 'alias_001_b', question: 'minimum investment for OptionSmart',               answer: faqs.find(f=>f.id==='faq_001')?.answer },
    { id: 'alias_001_c', question: 'what is the entry level capital requirement?',      answer: faqs.find(f=>f.id==='faq_001')?.answer },
    { id: 'alias_001_d', question: 'starting amount for optionsmart algo plan',         answer: faqs.find(f=>f.id==='faq_001')?.answer },
    { id: 'alias_006_a', question: 'what happens if algo loses too much money?',        answer: faqs.find(f=>f.id==='faq_006')?.answer },
    { id: 'alias_006_b', question: 'how does optionsmart protect my capital?',          answer: faqs.find(f=>f.id==='faq_006')?.answer },
    { id: 'alias_006_c', question: 'what safeguards are in place for losses?',          answer: faqs.find(f=>f.id==='faq_006')?.answer },
    { id: 'alias_011_a', question: 'how quickly can positions be closed in emergency?', answer: faqs.find(f=>f.id==='faq_011')?.answer },
    { id: 'alias_011_b', question: 'emergency stop for all trades',                     answer: faqs.find(f=>f.id==='faq_011')?.answer },
    { id: 'alias_011_c', question: 'can I instantly stop all algo trades?',             answer: faqs.find(f=>f.id==='faq_011')?.answer },
    { id: 'alias_029_a', question: 'can I withdraw my money anytime?',                  answer: faqs.find(f=>f.id==='faq_029')?.answer },
    { id: 'alias_029_b', question: 'is there a lock in period for optionsmart?',        answer: faqs.find(f=>f.id==='faq_029')?.answer },
    { id: 'alias_029_c', question: 'how long is capital locked with optionsmart?',      answer: faqs.find(f=>f.id==='faq_029')?.answer },
    { id: 'alias_030_a', question: 'is my money safe with optionsmart?',                answer: faqs.find(f=>f.id==='faq_030')?.answer },
    { id: 'alias_030_b', question: 'who holds my investment capital?',                  answer: faqs.find(f=>f.id==='faq_030')?.answer },
    { id: 'alias_030_c', question: 'does optionsmart hold my funds?',                   answer: faqs.find(f=>f.id==='faq_030')?.answer },
    { id: 'alias_009_a', question: 'is optionsmart legal in india?',                    answer: faqs.find(f=>f.id==='faq_009')?.answer },
    { id: 'alias_009_b', question: 'is this SEBI approved algo trading?',               answer: faqs.find(f=>f.id==='faq_009')?.answer },
    { id: 'alias_009_c', question: 'sebi registered algo platform india',               answer: faqs.find(f=>f.id==='faq_009')?.answer },
    { id: 'alias_009_d', question: 'what is sebi registration?',                        answer: faqs.find(f=>f.id==='faq_009')?.answer },
    { id: 'alias_012_a', question: 'how do I get started with optionsmart?',            answer: faqs.find(f=>f.id==='faq_012')?.answer },
    { id: 'alias_012_b', question: 'how do I sign up for algo trading?',                answer: faqs.find(f=>f.id==='faq_012')?.answer },
    { id: 'alias_012_c', question: 'what is the onboarding process?',                   answer: faqs.find(f=>f.id==='faq_012')?.answer },
    { id: 'alias_012_d', question: 'how to get started onboarding',                     answer: faqs.find(f=>f.id==='faq_012')?.answer },
    { id: 'alias_012_e', question: 'how to start onboarding',                           answer: faqs.find(f=>f.id==='faq_012')?.answer },
    { id: 'alias_014_a', question: 'does optionsmart keep positions overnight?',        answer: faqs.find(f=>f.id==='faq_014')?.answer },
    { id: 'alias_014_b', question: 'are there any open positions after market close?',  answer: faqs.find(f=>f.id==='faq_014')?.answer },
    { id: 'alias_003_a', question: 'what algos do you run?',                            answer: faqs.find(f=>f.id==='faq_003')?.answer },
    { id: 'alias_003_b', question: 'what strategies do you run?',                       answer: faqs.find(f=>f.id==='faq_003')?.answer },
    { id: 'alias_003_c', question: 'list of algo strategies',                           answer: faqs.find(f=>f.id==='faq_003')?.answer },
    { id: 'alias_003_d', question: 'how do algo strategies work?',                       answer: faqs.find(f=>f.id==='faq_003')?.answer },
  ];

  // 2. Extended aliases (from seedExtendedFaq.js)
  const extendedAliases = [
    { id: 'ext_alias_q01_a', question: 'why should I use optionsmart',           answer: allBase.find(d => d.id === 'faq_q01')?.answer },
    { id: 'ext_alias_q01_b', question: 'what makes optionsmart better',          answer: allBase.find(d => d.id === 'faq_q01')?.answer },
    { id: 'ext_alias_q01_c', question: 'optionsmart vs competitors advantages',   answer: allBase.find(d => d.id === 'faq_q01')?.answer },
    { id: 'ext_alias_q02_a', question: 'explain how algo strategies work',       answer: allBase.find(d => d.id === 'faq_q02')?.answer },
    { id: 'ext_alias_q02_b', question: 'how does saturn venus pluto work',        answer: allBase.find(d => d.id === 'faq_q02')?.answer },
    { id: 'ext_alias_q02_c', question: 'investment scheme optionsmart',           answer: allBase.find(d => d.id === 'faq_q02')?.answer },
    { id: 'ext_alias_q03_a', question: 'how much does optionsmart cost',          answer: allBase.find(d => d.id === 'faq_q03')?.answer },
    { id: 'ext_alias_q03_b', question: 'optionsmart subscription price',          answer: allBase.find(d => d.id === 'faq_q03')?.answer },
    { id: 'ext_alias_q03_c', question: 'fee charges of optionsmart platform',     answer: allBase.find(d => d.id === 'faq_q03')?.answer },
    { id: 'ext_alias_q04_a', question: 'is there an app for optionsmart',         answer: allBase.find(d => d.id === 'faq_q04')?.answer },
    { id: 'ext_alias_q04_b', question: 'optionsmart android app',                 answer: allBase.find(d => d.id === 'faq_q04')?.answer },
    { id: 'ext_alias_q04_c', question: 'optionsmart iphone ios app',              answer: allBase.find(d => d.id === 'faq_q04')?.answer },
    { id: 'ext_alias_q05_a', question: 'do I need to know coding for optionsmart',answer: allBase.find(d => d.id === 'faq_q05')?.answer },
    { id: 'ext_alias_q05_b', question: 'programming required for algo trading',   answer: allBase.find(d => d.id === 'faq_q05')?.answer },
    { id: 'ext_alias_q05_c', question: 'is optionsmart for non-technical users',  answer: allBase.find(d => d.id === 'faq_q05')?.answer },
    { id: 'ext_alias_q06_a', question: 'can I backtest before investing',         answer: allBase.find(d => d.id === 'faq_q06')?.answer },
    { id: 'ext_alias_q06_b', question: 'test strategy on historical data',        answer: allBase.find(d => d.id === 'faq_q06')?.answer },
    { id: 'ext_alias_q07_a', question: 'which markets does optionsmart trade in', answer: allBase.find(d => d.id === 'faq_q07')?.answer },
    { id: 'ext_alias_q07_b', question: 'does optionsmart trade nifty banknifty',  answer: allBase.find(d => d.id === 'faq_q07')?.answer },
    { id: 'ext_alias_q07_c', question: 'equity futures options commodity trading',answer: allBase.find(d => d.id === 'faq_q07')?.answer },
    { id: 'ext_alias_q08_a', question: 'can a beginner use optionsmart',          answer: allBase.find(d => d.id === 'faq_q08')?.answer },
    { id: 'ext_alias_q08_b', question: 'I am new to trading can I use optionsmart',answer: allBase.find(d => d.id === 'faq_q08')?.answer },
    { id: 'ext_alias_q08_c', question: 'no trading experience optionsmart',       answer: allBase.find(d => d.id === 'faq_q08')?.answer },
    { id: 'ext_alias_q09_a', question: 'tradingview charts with optionsmart',     answer: allBase.find(d => d.id === 'faq_q09')?.answer },
    { id: 'ext_alias_q09_b', question: 'does optionsmart support tradingview',    answer: allBase.find(d => d.id === 'faq_q09')?.answer },
    { id: 'ext_alias_q10_a', question: 'how to become a strategy developer',      answer: allBase.find(d => d.id === 'faq_q10')?.answer },
    { id: 'ext_alias_q10_b', question: 'sell my algo strategy optionsmart',       answer: allBase.find(d => d.id === 'faq_q10')?.answer },
    { id: 'ext_alias_q10_c', question: 'what is smartalgos',                      answer: allBase.find(d => d.id === 'faq_q10')?.answer },
    { id: 'ext_alias_q11_a', question: 'how much return does optionsmart give',   answer: allBase.find(d => d.id === 'faq_q11')?.answer },
    { id: 'ext_alias_q11_b', question: 'expected returns from optionsmart',       answer: allBase.find(d => d.id === 'faq_q11')?.answer },
    { id: 'ext_alias_q11_c', question: 'return on capital roc optionsmart',       answer: allBase.find(d => d.id === 'faq_q11')?.answer },
    { id: 'ext_alias_q12_a', question: 'does optionsmart hedge positions',        answer: allBase.find(d => d.id === 'faq_q12')?.answer },
    { id: 'ext_alias_q12_b', question: 'what is directional vs non directional',  answer: allBase.find(d => d.id === 'faq_q12')?.answer },
    { id: 'ext_alias_q13_a', question: 'which index does optionsmart trade',      answer: allBase.find(d => d.id === 'faq_q13')?.answer },
    { id: 'ext_alias_q13_b', question: 'nifty banknifty optionsmart strategies',  answer: allBase.find(d => d.id === 'faq_q13')?.answer },
    { id: 'ext_alias_q14_a', question: 'margin needed for optionsmart',           answer: allBase.find(d => d.id === 'faq_q14')?.answer },
    { id: 'ext_alias_q14_b', question: 'can I use pledged shares collateral',     answer: allBase.find(d => d.id === 'faq_q14')?.answer },
    { id: 'ext_alias_q14_c', question: 'what is the stop loss in optionsmart',    answer: allBase.find(d => d.id === 'faq_q14')?.answer },
    { id: 'ext_alias_q15_a', question: 'maximum loss in optionsmart',             answer: allBase.find(d => d.id === 'faq_q15')?.answer },
    { id: 'ext_alias_q15_b', question: 'what is drawdown in optionsmart',         answer: allBase.find(d => d.id === 'faq_q15')?.answer },
    { id: 'ext_alias_q15_c', question: 'how much can optionsmart lose per day',   answer: allBase.find(d => d.id === 'faq_q15')?.answer },
    { id: 'ext_alias_q16_a', question: 'optionsmart vs mutual fund which is better', answer: allBase.find(d => d.id === 'faq_q16')?.answer },
    { id: 'ext_alias_q16_b', question: 'why algo trading over mutual fund',       answer: allBase.find(d => d.id === 'faq_q16')?.answer },
    { id: 'ext_alias_q16_c', question: 'less than 15 percent return worth it',    answer: allBase.find(d => d.id === 'faq_q16')?.answer },
    { id: 'ext_alias_q17_a', question: 'what happens to strategy on budget day',  answer: allBase.find(d => d.id === 'faq_q17')?.answer },
    { id: 'ext_alias_q17_b', question: 'RBI policy impact on optionsmart algo',   answer: allBase.find(d => d.id === 'faq_q17')?.answer },
    { id: 'ext_alias_q17_c', question: 'how algo handles market crash news',      answer: allBase.find(d => d.id === 'faq_q17')?.answer },
    { id: 'ext_alias_q18_a', question: 'zerodha brokerage for optionsmart trades',answer: allBase.find(d => d.id === 'faq_q18')?.answer },
    { id: 'ext_alias_q18_b', question: 'how much brokerage is charged',           answer: allBase.find(d => d.id === 'faq_q18')?.answer },
    { id: 'ext_alias_q19_a', question: 'does optionsmart trade options futures',  answer: allBase.find(d => d.id === 'faq_q19')?.answer },
    { id: 'ext_alias_q19_b', question: 'weekly expiry options trading optionsmart',answer: allBase.find(d => d.id === 'faq_q19')?.answer },
    { id: 'ext_alias_q20_a', question: 'gold silver crude oil trading optionsmart',answer: allBase.find(d => d.id === 'faq_q20')?.answer },
    { id: 'ext_alias_q20_b', question: 'mcx commodity optionsmart',               answer: allBase.find(d => d.id === 'faq_q20')?.answer },
    { id: 'ext_alias_q22_a', question: 'which stocks should I invest in',         answer: allBase.find(d => d.id === 'faq_q22')?.answer },
    { id: 'ext_alias_q22_b', question: 'stock recommendations optionsmart',       answer: allBase.find(d => d.id === 'faq_q22')?.answer },
    { id: 'ext_alias_q23_a', question: 'what services does optionsmart provide',  answer: allBase.find(d => d.id === 'faq_q23')?.answer },
    { id: 'ext_alias_q23_b', question: 'optionsmart platform features',           answer: allBase.find(d => d.id === 'faq_q23')?.answer },
    { id: 'ext_alias_q24_a', question: 'is options trading riskier than equity',  answer: allBase.find(d => d.id === 'faq_q24')?.answer },
    { id: 'ext_alias_q24_b', question: 'options vs equity which is safer',        answer: allBase.find(d => d.id === 'faq_q24')?.answer },
    { id: 'ext_alias_q25_a', question: 'is optionsmart SEBI approved',            answer: allBase.find(d => d.id === 'faq_q25')?.answer },
    { id: 'ext_alias_q25_b', question: 'minimum capital to start optionsmart',    answer: allBase.find(d => d.id === 'faq_q25')?.answer },
    { id: 'ext_alias_q25_c', question: 'legal compliance optionsmart india',      answer: allBase.find(d => d.id === 'faq_q25')?.answer },
    { id: 'ext_alias_q26_a', question: 'can I use zerodha with optionsmart',      answer: allBase.find(d => d.id === 'faq_q26')?.answer },
    { id: 'ext_alias_q26_b', question: 'angel one optionsmart supported',         answer: allBase.find(d => d.id === 'faq_q26')?.answer },
    { id: 'ext_alias_q27_a', question: 'who manages my money in optionsmart',     answer: allBase.find(d => d.id === 'faq_q27')?.answer },
    { id: 'ext_alias_q27_b', question: 'optionsmart team who runs strategies',    answer: allBase.find(d => d.id === 'faq_q27')?.answer },
    { id: 'ext_alias_q28_a', question: 'can I earn referring clients to optionsmart', answer: allBase.find(d => d.id === 'faq_q28')?.answer },
    { id: 'ext_alias_q28_b', question: 'affiliate partner program optionsmart',   answer: allBase.find(d => d.id === 'faq_q28')?.answer },
    { id: 'ext_alias_q28_c', question: 'referral commission from optionsmart',    answer: allBase.find(d => d.id === 'faq_q28')?.answer },
    { id: 'ext_alias_q29_a', question: 'what are the benefits of optionsmart',    answer: allBase.find(d => d.id === 'faq_q29')?.answer },
    { id: 'ext_alias_q29_b', question: 'pros of using optionsmart algo trading',  answer: allBase.find(d => d.id === 'faq_q29')?.answer },
    { id: 'ext_alias_q30_a', question: 'free trial optionsmart',                  answer: allBase.find(d => d.id === 'faq_q30')?.answer },
    { id: 'ext_alias_q30_b', question: 'demo account optionsmart',                answer: allBase.find(d => d.id === 'faq_q30')?.answer },
    { id: 'ext_alias_q30_c', question: 'paper trading optionsmart',               answer: allBase.find(d => d.id === 'faq_q30')?.answer },
    { id: 'ext_alias_q31_a', question: 'trading course from optionsmart',         answer: allBase.find(d => d.id === 'faq_q31')?.answer },
    { id: 'ext_alias_q31_b', question: 'learn algo trading optionsmart',          answer: allBase.find(d => d.id === 'faq_q31')?.answer },
    { id: 'ext_alias_q32_a', question: 'how to register on optionsmart',          answer: allBase.find(d => d.id === 'faq_q32')?.answer },
    { id: 'ext_alias_q32_b', question: 'onboarding process optionsmart steps',    answer: allBase.find(d => d.id === 'faq_q32')?.answer },
    { id: 'ext_alias_q32_c', question: 'executive support during registration',   answer: allBase.find(d => d.id === 'faq_q32')?.answer },
    { id: 'ext_alias_q33_a', question: 'detailed explanation of optionsmart strategies', answer: allBase.find(d => d.id === 'faq_q33')?.answer },
    { id: 'ext_alias_q33_b', question: 'how exactly does saturn strategy work',   answer: allBase.find(d => d.id === 'faq_q33')?.answer },
    { id: 'ext_alias_q33_c', question: 'deep dive pluto directional strategy',    answer: allBase.find(d => d.id === 'faq_q33')?.answer },
    { id: 'ext_alias_q34_a', question: 'at what time does algo start trading',    answer: allBase.find(d => d.id === 'faq_q34')?.answer },
    { id: 'ext_alias_q34_b', question: 'what time does optionsmart square off',   answer: allBase.find(d => d.id === 'faq_q34')?.answer },
    { id: 'ext_alias_q34_c', question: 'build my own strategy on optionsmart',    answer: allBase.find(d => d.id === 'faq_q34')?.answer },
    { id: 'ext_alias_q35_a', question: 'step by step guide to start optionsmart', answer: allBase.find(d => d.id === 'faq_q35')?.answer },
    { id: 'ext_alias_q35_b', question: 'what do I need to start algo trading',    answer: allBase.find(d => d.id === 'faq_q35')?.answer },
    { id: 'ext_alias_q35_c', question: 'requirements to start with optionsmart',  answer: allBase.find(d => d.id === 'faq_q35')?.answer },
  ].filter(a => a.answer);

  return [...allBase, ...curatedAliases, ...extendedAliases].map(d => ({ ...d, type: 'curated' }));
}

module.exports = { getAllCuratedDocs };
